#The makefile for the paper

#Example code
ANOUTPUT = ../../gen/analysis/output #This line of code decides where we save our files

all: $(ANOUTPUT)'Select our csv here'

$(ANOUTPUT)/'Select our csv here': paper.md
	R --vanilla < paper.md 